// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etsrihgsqncdwlzsdtil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0c3JpaGdzcW5jZHdsenNkdGlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDI0MDAsImV4cCI6MjA3MzAxODQwMH0.aLwkoe8n_rif9pO7iy6XyDqsFzYvbOBEFTcP-SsMuLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});