name: Build and Deploy Dist

on:
  push:
    branches:
      - main  # run workflow only when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build project
      - name: Build project
        run: npm run build

      # 5. Deploy dist to distdeploy branch
      - name: Deploy dist folder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Switch to a new orphan branch
          git checkout --orphan distdeploy

          # Remove everything except dist
          git rm -rf .
          mv dist/* .   # move files from dist/ into root

          # Add & commit
          git add .
          git commit -m "Deploy dist folder"

          # Force push to distdeploy branch
          git push -f origin distdeploy
