name: Build dist to distdeploy

on:
  push:
    branches: [ main ]   # ⚠️ If your default branch is "master", change to [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build project
        run: npm run build

      - name: Deploy dist to distdeploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: distdeploy   # target branch
          folder: dist         # output folder
          clean: true
          single-commit: true
